#!/command/with-contenv sh

if [ "$WEB" == "true" ]; then
  echo "正在启动 darkhttpd 服务..."
  exec s6-setuidgid http darkhttpd /www --port 8080
else
  echo "未设置启动 darkhttpd 服务，退出！"
  s6-svc -Od .
  exit 0
fi