#!/command/with-contenv sh

#启动filebrowser
if [ "${ENABLE_FILEBROWSER}" = "true" ]; then
    echo "+正在启动 FileBrowser Quantum 服务..."
	exec s6-setuidgid download filebrowser -c /aria2/config/filebrowser_quantum_config.yaml 2>&1 | awk '{print "[FileBrowser Quantum] " $0}'
else
    s6-svc -Od .
    exit 0
fi