name: dockertest

on:
  push:
    paths:
    - 'Dockerfile'
    - 'rootfs/**'
  workflow_dispatch:

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Set env'
        run: |
          echo "DOCKERTEST_VER=test" >> $GITHUB_ENV
          sed -i "s@KMS_VER@$(echo `grep -n "KMS_VER=" Dockerfile`|awk -F= '{print $2}')@" rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.txt
          sed -i "s@DATE_TIME@$(date)@" rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.txt
          sed -i "s@VLMCSD_VER@$(echo `grep -n "VLMCSD_VER=" Dockerfile`|awk -F= '{print $2}')@" rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.txt
          sed -i "s@DARKHTTPD_VER@$(echo `grep -n "DARKHTTPD_VER=" Dockerfile`|awk -F= '{print $2}')@" rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.txt
          cat rootfs/etc/s6-overlay/s6-rc.d/init/00-banner.txt

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
#          platforms: linux/arm/v7
          push: true
          tags: |
            ghcr.io/dothebetter/dockertest:${{ env.DOCKERTEST_VER }}
            registry.cn-hangzhou.aliyuncs.com/dothebetter/dockertest:${{ env.DOCKERTEST_VER }}
